[GENERAL]
enable_twic_auto_dl = 1
twic_max = 1397
extract_pgn_files = 1
delete_zip_files = 1
merge_pgn_files = 1
delete_pgn_files = 1
convert_pgn_to_scid = 1
delete_remaining_pgn = 1
merge_scid_database = 1
write_zipped_scid_copy = 0
delete_scid_files = 1

[PATHS]
work_path = "/home/akr/pgn2scid_work_dir"
database_dir = "/home/akr/Chess_Mainbase/chess_main_db.si4"

